[#1]
        Ricorda è un semplice scadenziario che ti
	permette di registrare ogni evento che
	devi programmare nel tempo.

[#2]
	Ricorda ti aiuta a gestire le scadenze
	periodiche, sia annuali che mensili,
	mantenendole in automatico attuali.


[#3]

        Ricorda è semplice, compatto ed efficiente.

[#4]
	

        Registralo, Ricorda è un prodotto che ti conviene
	tenere in vista sul tuo computer.

