// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Ecom;

{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {RCFileType} {Ecom_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'Ecom_DRC.res' 'Ecom_DRC.rc'}

{$E ENU}

begin
end.
