; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Diesel2"
#define MyAppVersion "4.4.3"
#define MyAppPublisher "MLSoft"
#define MyAppExeName "Diesel2.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3CA197EE-DDDF-48A3-A064-36172436EFCB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile=C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\Diesel2\Readme.txt
InfoAfterFile=C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\Diesel2\Note.txt
OutputDir=C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\Diesel2\install
OutputBaseFilename=Diesel4.4.3_setup
SetupIconFile=C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\Diesel2\Diesel2_Icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\Diesel2\Diesel2.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\Diesel2\Diesel.chm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\Diesel2\DieselDB.ABS"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\Diesel2\Readme.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

