; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "HelpDesk"
#define MyAppVersion "2.3"
#define MyAppPublisher "MLSoft"
#define MyAppURL "https://sourceforge.net/projects/workstationhelp/"
#define MyAppExeName "HelpDesk.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8B1049E2-1212-49AF-9E8B-FF10DE4AD420}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile=C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\HlpDesk\Dsk\Readme.txt
OutputDir=C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\HlpDesk\Install
OutputBaseFilename=setupHelpDesk2.3
SetupIconFile=C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\HlpDesk\Dsk\ML13.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\HlpDesk\Dsk\HelpDesk.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\HlpDesk\Dsk\HelpDesk.ABS"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\HlpDesk\Dsk\helpdesk.chm"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\HlpDesk\Dsk\ML13.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Manlio Laschena\Documents\RAD Studio\Projects\2013\HlpDesk\Dsk\Readme.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

